### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by logic** [sstarcher/go-okta#1]
Hi,

I'm slowly trying to package up https://github.com/hashicorp/vault for Fedora, and part of that means putting together builds for all of the dependencies, of which go-okta is one. One hing that popped up while pulling it in was that there was no licensing information anywhere in the repo or in any of the source files.

Would you be willing to clarify what license you intended this to be available under? Preferably, with a LICENSE file in the repo, but just a "it's freely redistributable without restrictions" response here would be awesome.

Thanks, and sorry for the noise, licensing is annoying. :(

**Comment by derek-virtustream** [comment]
+1 on this. Otherwise somebody might need to vendor a copy of Vault where they've ripped out okta support.

**Comment by derek-virtustream** [comment]
Perhaps:
https://github.com/sstarcher/go-okta/pull/3

**Comment by sstarcher** [comment]
#3  closes this
