### ISSUE TITLE
Licensing Issues : For go-okta OSS license information 

### ISSUE THREAD

**Issue by sam0104** [sstarcher/go-okta#4]
As per https://github.com/sstarcher/go-okta/ no LICENSE file is available in the repo.
 It should have license information which can be used as open source product. Without license information we find it difficult to use.

Please include license file with information as part of https://github.com/sstarcher/go-okta/ which can be used as OSS .

Thanks
 Sas

**Comment by sstarcher** [comment]
#3  closes this
